### PR TITLE
Add vault_login_token filter docs

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Right now the only filter in this collection is not documented, resulting in https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_login_token_filter.html. Let's fix that :)

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
vault_login_token

### CODE REVIEW

**Comment by felixfontein** [comment]
The remaining errors seem to be unrelated to this PR.

**Comment by briantist** [comment]
Thanks for opening this @felixfontein ! I had started this back in #263 , but had issues with the support in core and how references to the page would work in the docsite (see comments there), which is why I didn't end up merging it. 

Perhaps somewhat similarly, the docs build does not seem to have picked up the changes in this PR (no build comment showing changes).

(the other failures are not related to this, they are due to `hvac==1.0.0` being released last night and will be resolved soon, see #301)

**Comment by felixfontein** [comment]
> Perhaps somewhat similarly, the docs build does not seem to have picked up the changes in this PR (no build comment showing changes).

Which is not surprising, since the docs build uses ansible-core 2.13. It would need to use `devel` to pick this up.

**Comment by felixfontein** [comment]
Closing in favor of #263.

**Pull request closed without merging**
