### PR TITLE
Add support for azure auth method

### PR DESCRIPTION
**Pull request by jchenship**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.hashi_vault/issues/78

Supports 3 types of azure auth 

- use a azure access token (`jwt`) directly 
- use azure service principal
- use azure managed identity 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

module_utils/_auth_method_azure.py

##### ADDITIONAL INFORMATION

Currently I'm not sure how to run unit tests locally, but I verify this on my azure vm with

###### jwt
```
jchen@vm-vault:~$ curl -s 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F&client_id=a57bbbed-d82a-4321-9d6f-abc89542730e' -H Metadata:true | jq
{
  "access_token": "[jwt]",
  "client_id": "a57bbbed-d82a-4321-9d6f-abc89542730e",
  "expires_in": "85943",
  "expires_on": "1660545929",
  "ext_expires_in": "86399",
  "not_before": "1660459229",
  "resource": "https://management.azure.com/",
  "token_type": "Bearer"
}
```
```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get vault secret
      community.hashi_vault.vault_kv2_get:
        url: https://vault.jchen.au:8200
        engine_mount_point: kv
        path: test
        auth_method: azure
        role_id: msi-vault
        jwt: "[jwt]"
      register: response

    - name: Debug vault response
      ansible.builtin.debug:
        msg:
          - "Secret: {{ response.secret }}"
          - "Data: {{ response.data }} (contains secret data & metadata in kv2)"
          - "Metadata: {{ response.metadata }}"
          - "Full response: {{ response.raw }}"
          - "Value of key 'FOO' in the secret: {{ response.secret.FOO }}"
```

```
jchen@vm-vault:~$ ansible-playbook ansible/kv_get.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************

TASK [Get vault secret] ****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug vault response] ************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Secret: {'FOO': 'bar'}",
        "Data: {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}} (contains secret data & metadata in kv2)",
        "Metadata: {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}",
        "Full response: {'request_id': 'd1555c0a-67e7-36e9-5353-bc638f867ff5', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}}, 'wrap_info': None, 'warnings': None, 'auth': None}",
        "Value of key 'FOO' in the secret: bar"
    ]
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

###### service principal

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get vault secret
      community.hashi_vault.vault_kv2_get:
        url: https://vault.jchen.au:8200
        engine_mount_point: kv
        path: test
        auth_method: azure
        role_id: msi-vault
        azure_tenant_id: "702a96ad-ac90-48e9-bbcb-759edc3ad591"
        azure_client_id: "8d74f877-fc8e-43bf-af74-481027e1a084"
        azure_client_secret: "[secret]"
      register: response

    - name: Debug vault response
      ansible.builtin.debug:
        msg:
          - "Secret: {{ response.secret }}"
          - "Data: {{ response.data }} (contains secret data & metadata in kv2)"
          - "Metadata: {{ response.metadata }}"
          - "Full response: {{ response.raw }}"
          - "Value of key 'FOO' in the secret: {{ response.secret.FOO }}"
```

```
jchen@vm-vault:~$ ansible-playbook ansible/kv_get.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [localhost] *******************************************************************************************************
TASK [Get vault secret] ************************************************************************************************ok: [localhost]

TASK [Debug vault response] ********************************************************************************************ok: [localhost] => {
    "msg": [
        "Secret: {'FOO': 'bar'}",
        "Data: {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}} (contains secret data & metadata in kv2)",
        "Metadata: {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}",
        "Full response: {'request_id': '42dc6f76-7d2e-7316-3d7f-d71ae8f3f043', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}}, 'wrap_info': None, 'warnings': None, 'auth': None}",
        "Value of key 'FOO' in the secret: bar"
    ]
}

PLAY RECAP *************************************************************************************************************localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

###### managed identity 

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get vault secret
      community.hashi_vault.vault_kv2_get:
        url: https://vault.jchen.au:8200
        engine_mount_point: kv
        path: test
        auth_method: azure
        role_id: msi-vault
        azure_client_id: "a57bbbed-d82a-4321-9d6f-abc89542730e"
      register: response

    - name: Debug vault response
      ansible.builtin.debug:
        msg:
          - "Secret: {{ response.secret }}"
          - "Data: {{ response.data }} (contains secret data & metadata in kv2)"
          - "Metadata: {{ response.metadata }}"
          - "Full response: {{ response.raw }}"
          - "Value of key 'FOO' in the secret: {{ response.secret.FOO }}"
```

result

```
jchen@vm-vault:~$ ansible-playbook ansible/kv_get.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************

TASK [Get vault secret] ****************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Debug vault response] ************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        "Secret: {'FOO': 'bar'}",
        "Data: {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}} (contains secret data & metadata in kv2)",
        "Metadata: {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}",
        "Full response: {'request_id': '85d6c8dd-cc7d-e7b5-817c-e69a5d21e383', 'lease_id': '', 'renewable': False, 'lease_duration': 0, 'data': {'data': {'FOO': 'bar'}, 'metadata': {'created_time': '2022-08-14T00:46:30.180160604Z', 'custom_metadata': None, 'deletion_time': '', 'destroyed': False, 'version': 1}}, 'wrap_info': None, 'warnings': None, 'auth': None}",
        "Value of key 'FOO' in the secret: bar"
    ]
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by briantist** [comment]
Hi @jchenship ! Thanks for opening this MR!

> Currently I'm not sure how to run unit tests locally, but I verify this on my azure vm with

Check out the [Contributor guide](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/contributor_guide.html) for how to check out the collection to the proper directory structure.

From there, you can run:

```
ansible-test units --docker default
```

If you have trouble running the container, you can try to run the same with `ansible-core>=2.11,<2.12` because the newer containers sometimes have issues running locally.

As an alternative, you can try:
```
ansible-test units --venv --requirements
```

I've kicked off a CI run, and here's the result of the unit tests:
https://github.com/ansible-collections/community.hashi_vault/runs/7846893677?check_suite_focus=true

It seems at a minimum you'll need to add your requirements to [`tests/unit/requirements.txt`](https://github.com/ansible-collections/community.hashi_vault/blob/main/tests/unit/requirements.txt) so that they get installed properly when the tests are run.

Unfortunately since you're a new contributor, I have to click the button to allow CI to run for every change you push, so it will be much faster for you to get the tests running locally.

---

I haven't looked very deeply at the changes yet, but on the surface they look good.

In addition to unit tests, you'll also need integration tests. Since we don't have access to Azure in the CI, we can do this via MMock to mock the responses from Vault. This is how we test AWS and LDAP right now, so you can take a look at how that works.

This is described a little bit in this comment https://github.com/ansible-collections/community.hashi_vault/issues/78#issuecomment-999223445 and also in the [Contributor guide](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/docsite/contributor_guide.html).

Since you've already got a fixture in place for the units, adding the appropriate mocks in MMock should be relatively easy as well.

---

Minor nit: update the copyright name and date in the files you're adding.

---

The sanity tests in the collection have been failing in the collection recently with these errors:
https://github.com/ansible-collections/community.hashi_vault/runs/7839632355?check_suite_focus=true#step:8:124

I have not had the time to investigate and fix those; they will fail for you too, you may ignore those for now, however do not ignore any other sanity test failures you see.

Sanity tests can be run locally too:
```
ansible-test sanity --docker default
```

---

It's ok if you can't get the hang of all the pieces, I can help get that stuff over the line, but it may take a little while. You've caught me at a time where I have a lot going on and will be out of town until next week, so I apologize for slow responses.

**Comment by jchenship** [comment]
@briantist thanks a lot for the tips and feedback, I'm quite busy at work in the weekdays as well, I will continue to work on this during the weekend because

**Comment by jchenship** [comment]
@briantist I fixed unit tests and added integration tests, they passed in CI. So requesting a review, thank you!

The only thing is there're failed sanity tests but don't seem to be related to by changes so I'm not sure what to do with it.

**Comment by briantist** [comment]
@jchenship thank you! This is looking great, I think nearly complete. I just landed #297 which will fix the sanity tests.

Please rebase so we can get the full CI run and see coverage.

---

We'll still need at least a few minor changes, but let's push up the rebase first to get the CI complete.

Small changes needed after that:
* [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment)
* fix copyright year and name in your new files
* add `version_added:` to the new options

---

I would like to release the collection version 3.2.0 today or tomorrow, because it contains a bugfix that has already affected some users (#294). If we can finish this up quickly, we can include this in 3.2.0 also.

If not, I will look to release that first, and this can go into 3.3.0, which is not a problem at all, I have no issue with making a new release very quickly after the other one.

**Comment by jchenship** [comment]
@briantist Hey I have fixed all the things you mentioned, please have another review, and release it in 3.2.0 if it's ok, thank you! Otherwise I will continue to fix it and hopefully we can release it in 3.3.0

**Review by briantist — COMMENTED** [review]
I'm making some suggestions here that are mostly about wording/text changes.
I will accept commit these changes right away, but if you disagree with any of them we can discuss and change them to something else.

I have some other code changes but they are hard to do via review comments, so I will check out your PR and push some changes directly to your branch.

I'll let you know when ready so you can pull down the commits, and look over the changes I've made.

Thanks again, this is really great!

**Review by briantist — APPROVED** [review]
@jchenship I think this is ready to go, please have a look at the commits I added and let me know if you think any other changes are needed, or if you have questions.

I tried to make smaller commits so it is easier to see what changes I made, I hope it's helpful.

**Comment by jchenship** [comment]
@briantist Yeah that looks good to me, thanks for your help to refine the PR, look forward for it to be released!

**Comment by briantist** [comment]
@jchenship thank you so much for this contribution! I hope you'll consider more in the future :)

This is now released as part of [version 3.2.0](https://github.com/ansible-collections/community.hashi_vault/releases/tag/3.2.0)! 🎉

**Pull request merged**
